replicaCount: 1

image:
  repository: CHANGE_ME_ECR_REPO_URL
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 5000

env:
  DB_HOST: "devops-cyber-assessment-db"
  DB_PORT: "5432"
  DB_NAME: "devops-cyber-assessment"
  DB_USER: "postgres"
  DB_PASSWORD: "oh-no!"
