image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

postgresql:
  database: devops-cyber-assessment
  username: postgres
  password: oh-no!

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi