apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: capitec
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiaW5mcmFieXRlIiwKICAgICAgInBhc3N3b3JkIjogImdocF9ZVXI5c3ZReThFb0RQY3hpcjdjaUdUaGJZeHhWaGc0OHF2a2QiLAogICAgICAiYXV0aCI6ICJhVzVtY21GaWVYUmxPanhaVDFWU1gwZEpWRWhWUWw5UVFWUSsiCiAgICB9CiAgfQp9Cg==
---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: capitec
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: git@github.com:infrabyte/capitec.git
    targetRevision: main
    path: helm/devops-cyber-assessment

  destination:
    server: https://kubernetes.default.svc
    namespace: capitec

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
