# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: monitoring
#   namespace: monitoring
# spec:
#   ingressClassName: nginx

#   rules:
#   - host: grafana.jumphost
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: monitoring-grafana
#             port:
#               number: 3000
