replicaCount: 1

image:
  repository: ghcr.io/infrabyte/capitec
  tag: "latest"
  pullPolicy: Always

service:
  port: 5000

env:
  DB_HOST: postgresql.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: devops-cyber-assessment
  DB_USER: postgres
  DB_PASSWORD: oh-no!
